#!/bin/bash


################################
### Source + Calibrator ###
################################

####isz399

#1213-172
#0823-500
#1934-638

# Do the calibration for each measurement set

################################
### Calibration of ATCA data ###
################################

mkdir 2100
mkdir 5500
mkdir 9000
mkdir Original_MSfiles


#########################################################################
### Load data by first flagging, split into targets, further flagging ###
#########################################################################

atlod in='*.C3041' out=c3041.uv ifsel=2 options=birdie,xycorr,rfiflag,noauto
uvsplit vis=c3041.uv

rm -r *.2100

mv *.9000 ./9000
mv c3041.uv ./9000


atlod in='*.C3041' out=c3041.uv ifsel=1 options=birdie,xycorr,rfiflag,noauto
uvsplit vis=c3041.uv

mv *.2100 ./2100
mv *.5500 ./5500
mv c3041.uv ./5500

mv *.C3041 ./Original_MSfiles

################################
################################
###     Central Frequency -  2100     ###
################################
################################


#########################################################################
### Load data by first flagging, split into targets, further flagging ###
#########################################################################

cd ./2100


### First flag the edges
uvflag vis=1213-172.2100 edge=40 flagval=flag
uvflag vis=isz399.2100 edge=40 flagval=flag
uvflag vis=0823-500.2100 edge=40 flagval=flag


### Check the visibilities of the flux calibrator
uvspec vis=0823-500.2100 stokes=xx,yy,xy,yx axis=chan,amp device=/xs nxy=5,3 interval=30


##################################
######## - RFI Flagging - ########
##################################

###### Flux Calibration

pgflag vis=0823-500.2100 stokes=i,q,u,v flagpar=8,5,5,3,6,3 "command=<b" device=/xs
pgflag vis=0823-500.2100 stokes=i,v,u,q flagpar=8,2,2,3,6,3 "command=<b" device=/xs
pgflag vis=0823-500.2100 stokes=i,v,q,u flagpar=8,2,2,3,6,3 "command=<b" device=/xs

### Check the visibilities of the flux calibrator
uvspec vis=0823-500.2100 stokes=xx,yy,xy,yx axis=chan,amp device=/xs nxy=5,3 interval=30


### Do a preliminary bandpass
mfcal vis=0823-500.2100 interval=0.1

### Check the visibilities of the flux calibrator
uvspec vis=0823-500.2100 stokes=xx,yy,xy,yx axis=chan,amp device=/xs nxy=5,3 interval=30


#to flag manually through the  bgflag or pgflag mode
blflag vis=0823-500.2100 stokes=xx,yy device=/xs axis=chan,amp options=nofqav,nobase
blflag vis=0823-500.2100 stokes=xy,yx device=/xs axis=chan,amp options=nofqav,nobase
pgflag vis=0823-500.2100 stokes=i,q,u,v device=/xs


### Do a new bandpass and a new plot 
mfcal vis=0823-500.2100 interval=0.1
uvspec vis=0823-500.2100 stokes=xx,yy,xy,yx axis=chan,amp device=/xs nxy=5,3 interval=30

### Check for RFI with freq-amp plot
uvplt vis=0823-500.2100  stokes=xx,yy axis=freq,amp device=/xs options=nobase,nofqav

### Derive the gains and instrumental leakage
gpcal vis=0823-500.2100 interval=0.1 nfbin=4 options=xyvary

### Plot the gains
uvplt vis=0823-500.2100 device=/xs stokes=i,q,u,v axis=real,imag options=equal,nobase,nofqav
uvplt vis=0823-500.2100 stokes=xx,yy axis=time,amp yrange=0,10 device=/xs nxy=5,3


###### Phase Calibration
gpcopy vis=0823-500.2100 out=1213-172.2100
uvspec vis=1213-172.2100 stokes=xx,yy,xy,yx axis=chan,amp device=/xs nxy=5,3 interval=30

### Flag the phase calibrator and re-check visibilities
pgflag vis=1213-172.2100 device=/xs stokes=i,q,u,v flagpar=8,5,5,3,6,3 command="=<b"
pgflag vis=1213-172.2100 device=/xs stokes=i,v,u,q flagpar=8,2,2,3,6,3 command="=<b"
pgflag vis=1213-172.2100 device=/xs stokes=i,v,q,u flagpar=8,2,2,3,6,3 command="=<b"
uvspec vis=1213-172.2100 select= stokes=xx,yy interval=60 axis=freq,phase device=/xs yrange=-185,185

uvspec vis=1213-172.2100  stokes=xx,yy,xy,yx axis=chan,amp device= /xs nxy=5,3 interval=30

# flag manually through the  bgflag or pgflag mode
blflag vis=1213-172.2100 stokes=xx,yy device=/xs axis=chan,phase options=nofqav,nobase
pgflag vis=1213-172.2100 stokes=i,q,u,v device=/xs

### Do the phase calibrator calibration and bootstrapping (pol)
gpcal vis=1213-172.2100 nfbin=4 interval=0.1 options=xyvary,qusolve,nopol refant=1
gpboot vis=1213-172.2100 cal=0823-500.2100


### Check for RFI with the freq-phase plot
uvplt vis=1213-172.2100 stokes=xx,yy axis=freq,phase device=/xs options=nobase,nofqav yrange=-180,180



###############################################
### Correct flux scale (NOT NEEDED IF 1934) ###
###############################################

mfboot vis=0823-500.2100,1213-172.2100 select='source(1934-638)’

##################################
#### - Imaging Preparation - #####
##################################

gpcopy vis=1213-172.2100 out=isz399.2100
gpaver vis=isz399.2100 interval=2 
pgflag vis=isz399.2100 device=/xs stokes=i,q,u,v flagpar=8,5,5,3,6,3 command="=<b"
pgflag vis=isz399.2100 device=/xs stokes=i,v,u,q flagpar=8,2,2,3,6,3 command="=<b"
pgflag vis=isz399.2100 device=/xs stokes=i,v,q,u flagpar=8,2,2,3,6,3 command="=<b"


uvplt vis=isz399.2100 stokes=xx,yy axis=freq,amp device=/xs options=nobase,nofqav

### Create a copy to continue working with, to not touch the calibrated data
uvaver vis=isz399.2100 out=isz399.2100.aver


# only if you need to flag data manually
blflag vis=isz399.2100 stokes=xx,yy device=/xs axis=chan,amp options=nofqav,nobase yrange=0.5
pgflag vis=isz399.2100.aver stokes=i,q,u,v device=/xs







################################
################################
###     Central Frequency -  5500     ###
################################
################################
cd ..
cd 5500

### First flag the edges
uvflag vis=1213-172.5500 edge=40 flagval=flag
uvflag vis=0823-500.5500 edge=40 flagval=flag
uvflag vis=isz399.5500 edge=40 flagval=flag


### Check the visibilities of the flux calibrator
uvspec vis=0823-500.5500 stokes=xx,yy,xy,yx axis=chan,amp device=/xs nxy=5,3 interval=30


##################################
######## - RFI Flagging - ########
##################################

###### Flux Calibration

pgflag vis=0823-500.5500 stokes=i,q,u,v flagpar=8,5,5,3,6,3 "command=<b" device=/xs
pgflag vis=0823-500.5500 stokes=i,v,u,q flagpar=8,2,2,3,6,3 "command=<b" device=/xs
pgflag vis=0823-500.5500 stokes=i,v,q,u flagpar=8,2,2,3,6,3 "command=<b" device=/xs

### Check the visibilities of the flux calibrator
uvspec vis=0823-500.5500 stokes=xx,yy,xy,yx axis=chan,amp device=/xs nxy=5,3 interval=30


### Do a preliminary bandpass
mfcal vis=0823-500.5500 interval=0.1

### Check the visibilities of the flux calibrator
uvspec vis=0823-500.5500 stokes=xx,yy,xy,yx axis=chan,amp device=/xs nxy=5,3 interval=30

### Check for RFI with freq-amp plot
uvplt vis=0823-500.5500  stokes=xx,yy axis=freq,amp device=/xs options=nobase,nofqav

### Derive the gains and instrumental leakage
gpcal vis=0823-500.5500 interval=0.1 nfbin=4 options=xyvary

###### Phase Calibration
gpcopy vis=0823-500.5500 out=1213-172.5500

### Flag the phase calibrator and re-check visibilities
pgflag vis=1213-172.5500 device=/xs stokes=i,q,u,v flagpar=8,5,5,3,6,3 command="=<b"
pgflag vis=1213-172.5500 device=/xs stokes=i,v,u,q flagpar=8,2,2,3,6,3 command="=<b"
pgflag vis=1213-172.5500 device=/xs stokes=i,v,q,u flagpar=8,2,2,3,6,3 command="=<b"

### Do the phase calibrator calibration and bootstrapping (pol)
gpcal vis=1213-172.5500 nfbin=4 interval=0.1 options=xyvary,qusolve,nopol refant=1
gpboot vis=1213-172.5500 cal=0823-500.5500

### Check for RFI with the freq-phase plot
uvplt vis=1213-172.5500 stokes=xx,yy axis=freq,phase device=/xs options=nobase,nofqav yrange=-180,180


###############################################
### Correct flux scale (NOT NEEDED IF 1934) ###
###############################################

mfboot vis=0823-500.5500,1213-172.5500 select='source(1934-638)'

##################################
#### - Imaging Preparation - #####
##################################

gpcopy vis=1213-172.5500 out=isz399.5500
gpaver vis=isz399.5500 interval=2 
pgflag vis=isz399.5500 device=/xs stokes=i,q,u,v flagpar=8,5,5,3,6,3 command="=<b"
pgflag vis=isz399.5500 device=/xs stokes=i,v,u,q flagpar=8,2,2,3,6,3 command="=<b"
pgflag vis=isz399.5500 device=/xs stokes=i,v,q,u flagpar=8,2,2,3,6,3 command="=<b"



uvplt vis=isz399.5500 stokes=xx,yy axis=freq,amp device=/xs options=nobase,nofqav

### Create a copy to continue working with, to not touch the calibrated data
uvaver vis=isz399.5500 out=isz399.5500.aver


# only if you need to flag data manually
blflag vis=isz399.5500 stokes=xx,yy device=/xs axis=chan,amp options=nofqav,nobase yrange=0.5
pgflag vis=isz399.5500.aver stokes=i,q,u,v device=/xs








################################
################################
###     Central Frequency -  9000     ###
################################
################################
cd ..
cd 9000

### First flag the edges
uvflag vis=1213-172.9000 edge=40 flagval=flag
uvflag vis=0823-500.9000 edge=40 flagval=flag
uvflag vis=isz399.9000 edge=40 flagval=flag


### Check the visibilities of the flux calibrator
uvspec vis=0823-500.9000 stokes=xx,yy,xy,yx axis=chan,amp device=/xs nxy=5,3 interval=30


##################################
######## - RFI Flagging - ########
##################################

###### Flux Calibration

pgflag vis=0823-500.9000 stokes=i,q,u,v flagpar=8,5,5,3,6,3 "command=<b" device=/xs
pgflag vis=0823-500.9000 stokes=i,v,u,q flagpar=8,2,2,3,6,3 "command=<b" device=/xs
pgflag vis=0823-500.9000 stokes=i,v,q,u flagpar=8,2,2,3,6,3 "command=<b" device=/xs

### Check the visibilities of the flux calibrator
uvspec vis=0823-500.9000 stokes=xx,yy,xy,yx axis=chan,amp device=/xs nxy=5,3 interval=30


### Do a preliminary bandpass
mfcal vis=0823-500.9000 interval=0.1

### Check the visibilities of the flux calibrator
uvspec vis=0823-500.9000 stokes=xx,yy,xy,yx axis=chan,amp device=/xs nxy=5,3 interval=30

### Check for RFI with freq-amp plot
uvplt vis=0823-500.9000  stokes=xx,yy axis=freq,amp device=/xs options=nobase,nofqav

### Derive the gains and instrumental leakage
gpcal vis=0823-500.9000 interval=0.1 nfbin=4 options=xyvary

###### Phase Calibration
gpcopy vis=0823-500.9000 out=1213-172.9000

### Flag the phase calibrator and re-check visibilities
pgflag vis=1213-172.9000 device=/xs stokes=i,q,u,v flagpar=8,5,5,3,6,3 command="=<b"
pgflag vis=1213-172.9000 device=/xs stokes=i,v,u,q flagpar=8,2,2,3,6,3 command="=<b"
pgflag vis=1213-172.9000 device=/xs stokes=i,v,q,u flagpar=8,2,2,3,6,3 command="=<b"

### Do the phase calibrator calibration and bootstrapping (pol)
gpcal vis=1213-172.9000 nfbin=4 interval=0.1 options=xyvary,qusolve,nopol refant=1
gpboot vis=1213-172.9000 cal=0823-500.9000


### Check for RFI with the freq-phase plot
uvplt vis=1213-172.9000 stokes=xx,yy axis=freq,phase device=/xs options=nobase,nofqav yrange=-180,180



###############################################
### Correct flux scale (NOT NEEDED IF 1934) ###
###############################################

mfboot vis=0823-500.9000,1213-172.9000 select='source(1934-638)'

##################################
#### - Imaging Preparation - #####
##################################

gpcopy vis=1213-172.9000 out=isz399.9000
gpaver vis=isz399.9000 interval=2 
pgflag vis=isz399.9000 device=/xs stokes=i,q,u,v flagpar=8,5,5,3,6,3 command="=<b"
pgflag vis=isz399.9000 device=/xs stokes=i,v,u,q flagpar=8,2,2,3,6,3 command="=<b"
pgflag vis=isz399.9000 device=/xs stokes=i,v,q,u flagpar=8,2,2,3,6,3 command="=<b"



uvplt vis=isz399.9000 stokes=xx,yy axis=freq,amp device=/xs options=nobase,nofqav

### Create a copy to continue working with, to not touch the calibrated data
uvaver vis=isz399.9000 out=isz399.9000.aver


# only if you need to flag data manually
blflag vis=isz399.9000 stokes=xx,yy device=/xs axis=chan,amp options=nofqav,nobase yrange=0.5
pgflag vis=isz399.9000.aver stokes=i,q,u,v device=/xs



